### ISSUE TITLE
[Feature] show "Scans on this Planet" as well as "Scans in this System"

### ISSUE THREAD

**Issue by slippycheeze** [Balvald/ArtemisScannerTracker#36]
**Is your feature request related to a problem? Please describe.**
Sometimes I lose track in my head of where I am on scanning a planet; I know it has five bio signals, but I can't remember if I have scanned all of them or not.   (eg: I exited the game on a planet after scanning, went to sleep, work, and then next evening have no idea where exactly I was at.)

Right now I open up the "Scans in this System", then mentally cross-reference the number of recorded scans for the planet I'm on and the number of bio signals found on the planet.   Works, but is mental effort.

**Describe the solution you'd like**
Show "on this planet:" as well as "in this system:" in the summary line for scans:
![annotated image of the UI component showing where I imagine the display showing](https://user-images.githubusercontent.com/306753/211196915-9bc8f418-5a2a-49cd-b2db-a6460ad241bc.png)

In the illustration I show "1/3" scans on the planet; I'd *love* if this kept track of the number of biological signals on the planet and showed progress like that.   
Simply showing the count "for the current planet" when that context exists would be super useful alone, though.

**Describe alternatives you've considered**
I actually get some of this feedback from the EDMC-Canonn plugin, which tracks the total number of biological signals for the current planet (if you open that part of the UI) and if I have personally hit them with the comp-scanner.  

Sadly, there is a big difference between "comp-scanned" and "took three successful bio samples", meaning it sometimes falls down because (a) I comp-scan something to record the location, since it is hard to find and I'm in the middle of sampling another bio type, or (b) I comp-scan something, but don't actually sample it, or (c) I sample something, and completely forget to comp-scan any of the three locations.

**Additional context**
I considered making a separate feature request for remembering the number of biological signals on the planet and/or asking spansh/EDSM about it.  I didn't think it was worth it, but if you want I'll split it off.

I'd like it if the "on this planet" and "on this system" indicators went green, or showed a nice ticked box, when they were fully sampled, too.  Something to say "job done, time to go ~~home~~ on to the next system."

PS: thank you again for the wonderful tool.  I am extremely happy to have it, and it is one of the most frequently used tools in my EDMC stack.

**Comment by Balvald** [comment]
What I have locally all the time (and technically already have locally) is the amount for each planet. that just needs to be displayed differently once we end up in the vicinity of a planet. (gotta remind myself if to check status.json again)

The information I do not have locally all the time would be the max amount of plant species.
If edmc-canonn is installed might be easiest to piggyback off of it for that specific info and yoink it from there because in python nothings really private.
if its not do the same type of api call, whether my plugin could also report and contribute to said database in the case of edmc-cannon not being installed I do not know.

Otherwise a way thats completely detached from edmc-canonn and any of their resources would be to prompt the user to use the dss and save it locally if and only if theres biosignals (otherwise not relevant to the plugin).

But definitly another feature to add to the journalcrawler aswell. That way it could go through everything check the dss scans and retroactively create the user's database of "known" but unscanned biosignals and by extension the progress the CMDR made on it.

Atleast if I remember correctly what info is part of the detailed scans in the journals (could be that the info for max number is in there but not the species, would still be better than nothing)

**Comment by Balvald** [comment]
"event":"SAASignalsFound" is the event that holds the info of max bioscans for each planet.

it happens after a DSS scan of the planet.
after we check for and find an entry where entry["event"] is  "SAASignalsFound"
then check entry["Signals"][i]["Type"] for all element in entry["Signals"]
if it is "$SAA_SignalType_Biological;" then we can grab for the corresponding i entry["Signals"][i]["Count"] which is the max amount of biological signals aka amount of plant species on the planet.

**Comment by Balvald** [comment]
after triggering that event for a planet it doesn't appear again when using the dss scanner.
It will only appear once?
